In [1]:
# GENERAL UTILITIES
import os
import pywt
import numpy as np
import pandas as pd
from glob import glob
import seaborn as sns
from  tqdm.notebook import tqdm
from matplotlib import pyplot as plt
%matplotlib inline

# MODEL DEVELOPMENT DEPENDENCIES


from sklearn.model_selection import KFold, StratifiedKFold
from sklearn.multioutput import MultiOutputRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error
from sklearn import preprocessing

In [2]:
# SOME CONSTANTS UTILIZED IN THE NOTEBOOK
DEBUG = False 
AUGMENT_CONSTANT_RF=1 
AUGMENT_CONSTANT_KNN=1 
LABEL_NAMES = ["P", "K", "Mg", "pH"] 
#LABEL_MAXS = np.array([325.0, 625.0, 400.0, 7.8]) 
LABEL_MAXS = np.array([1, 1, 1, 1]) 
#Y_BASE_FACT = np.array([121764.2 / 1731.0, 394876.1 / 1731.0, 275875.1 / 1731.0, 11747.67 / 1731.0]) / LABEL_MAXS 
COL_IX = [0, 1, 2, 3]

In [3]:
def load_data(directory: str, gt_file_path: str, is_train=True, augment_constant: int = 0):
    """Load each cube, reduce its dimensionality and append to array.

    Args:
        directory (str): Directory to either train or test set
        gt_file_path (str): File path for the ground truth labels (expected CVS file)
        is_train (boolean): Binary flag for setting loader for Train (TRUE) or Test (FALSE)
        augment_constant (int): number of augmentation steps to randomly crop from the larger agricultural fields
    Returns:
        [type]: Tuple of lists composed of raw field (data , mask) pairs,
                and if exists: (augmented data, augmented mask) pairs, and ground truth labels
    """
    
    datalist = []
    masklist = []
    aug_datalist = []
    aug_masklist = []
    aug_labellist = []

    if is_train:
        labels = load_gt(gt_file_path)

    all_files = np.array(
        sorted(
            glob(os.path.join(directory, "*.npz")),
            key=lambda x: int(os.path.basename(x).replace(".npz", "")),
        )
    )

    if DEBUG:
        all_files = all_files[:100]
        if is_train:
            labels = labels[:100]

    for idx, file_name in tqdm(enumerate(all_files),total=len(all_files), desc="Loading {} data .."
                               .format("training" if is_train else "test")):
       # We load the data into memory as provided in the example notebook of the challenge
        with np.load(file_name) as npz:
            mask = npz["mask"]
            data = npz["data"]
            datalist.append(data)
            masklist.append(mask)
            
    # for training data we make pre-augmentation by adding some randomly cropped samples
    if is_train: 
        for i in range(augment_constant):
            for idx, file_name in tqdm(enumerate(all_files),total=len(all_files), desc="Loading augmentation {} ..".format(i+1)):
                # print(file_name)
                with np.load(file_name) as npz:
                    flag = True
                    mask = npz["mask"]
                    data = npz["data"]
                    ma = np.max(data, keepdims=True)
                    sh = data.shape[1:]
                    for i in range(0): 
                        # Repeating 11x11 cropping 10 times does not mean we use all croppings:
                        # as seen in the Flag=False below at the end of the loop, 
                        # when we reach at the good crop (not coinciding to the masked area) we stop searching 
                        
                        # Randomly cropping the fields with 11x11 size, 
                        # and adding some noise to the cropped samples 
                        edge = 11  
                        x = np.random.randint(sh[0] + 1 - edge)
                        y = np.random.randint(sh[1] + 1 - edge)
                        
                        # get crops having meaningful pixels, not zeros
                        if np.sum(mask[0, x : (x + edge), y : (y + edge)]) > 120: 
                            aug_data = (data[:, x : (x + edge), y : (y + edge)]
                                        + np.random.uniform(-0.01, 0.01, (150, edge, edge)) * ma)
                            aug_mask = mask[:, x : (x + edge), y : (y + edge)] | np.random.randint(0, 1, (150, edge, edge))
                            
                            flag = False #break the loop when you have a meaningful crop
                            break

                    # After having  11x11 croped sample, get another crop considering 
                    # the minimum edge length: (min_edge,min_edge)
                    if flag: 
                        max_edge = np.max(sh)
                        min_edge = np.min(sh)  # AUGMENT BY SHAPE
                        edge = min_edge  # np.random.randint(16, min_edge)
                        x = np.random.randint(sh[0] + 1 - edge)
                        y = np.random.randint(sh[1] + 1 - edge)
                        aug_data = (data[:, x : (x + edge), y : (y + edge)]
                                    + np.random.uniform(-0.001, 0.001, (150, edge, edge)) * ma)
                        aug_mask = mask[:, x : (x + edge), y : (y + edge)] | np.random.randint(0, 1, (150, edge, edge))

                    aug_datalist.append(aug_data)
                    aug_masklist.append(aug_mask)
                    aug_labellist.append(
                        labels[idx, :]
                        + labels[idx, :] * np.random.uniform(-0.001, 0.001, 4)
                    )

    # do pre-augmentation only for training data
    if is_train: 
        return (datalist,
                masklist,
                labels,
                aug_datalist,
                aug_masklist,
                np.array(aug_labellist))
    else:
        return datalist, masklist


def load_gt(file_path: str):
    """Load labels for train set from the ground truth file.
    Args:
        file_path (str): Path to the ground truth .csv file.
    Returns:
        [type]: 2D numpy array with soil properties levels
    """
    gt_file = pd.read_csv(file_path)
    labels = gt_file[["P", "K", "Mg", "pH"]].values / LABEL_MAXS  # normalize ground-truth between 0-1
    
    return labels

In [5]:
# Please be sure that the directory and file locations are given correctly in your own system
train_data_dir = '/kaggle/input/soil-hyperspectral-images/train_data/train_data/train_data'
test_data_dir=  '/kaggle/input/soil-hyperspectral-images/test_data/test_data'
gt_data_path = '/kaggle/input/soil-hyperspectral-images/train_data/train_data/train_gt.csv'

# Loading training raw data
X_train, M_train, y_train, X_aug_train, M_aug_train, y_aug_train = load_data(train_data_dir, 
                                                                             gt_data_path, 
                                                                             is_train=True, 
                                                                             augment_constant=AUGMENT_CONSTANT_KNN)
# Loading test raw data
X_test, M_test = load_data(test_data_dir, 
                           gt_file_path=None, 
                           is_train=False)

print(f"Train data size: {len(X_train)}")
print(f"Train aug data size: {len(X_aug_train)}")
print(f"Test data size: {len(X_test)}")

Loading training data ..:   0%|          | 0/1732 [00:00<?, ?it/s]

Loading augmentation 1 ..:   0%|          | 0/1732 [00:00<?, ?it/s]

Loading test data ..:   0%|          | 0/1154 [00:00<?, ?it/s]

Train data size: 1732
Train aug data size: 1732
Test data size: 1154

In [6]:
def preprocess(data_list, mask_list, is_for_KNN=False): 
    """Extract high-level features from the raw field data.

    Args:
        data_list: Directory to either train or test set
        mask_list: File path for the ground truth labels (expected CVS file)
        is_for_KNN: Binary flag for determining if the features are generated for KNN (TRUE) or Random Forest (FALSE)
    Returns:
        [type]: Tuple of lists composed of (features , field size) pairs for each field, 
                where field size will be used performance analysis.
    """
        
    def _shape_pad(data):
        # This sub-function makes padding to have square fields sizes.
        # Not mandatory but eliminates the risk of calculation error in singular value decomposition,
        # padding by warping also improves the performance slightly.
        max_edge = np.max(image.shape[1:])
        shape = (max_edge, max_edge)
        padded = np.pad(data,((0, 0), (0, (shape[0] - data.shape[1])), (0, (shape[1] - data.shape[2]))),"wrap")
        return padded
    
    filtering = SpectralCurveFiltering()
    w1 = pywt.Wavelet("sym3")
    w2 = pywt.Wavelet("dmey")

    processed_data = []
    average_edge = []

    for idx, (data, mask) in enumerate(
        tqdm(
            zip(data_list, mask_list),
            total=len(data_list),
            position=0,
            leave=True,
            desc="INFO: Preprocessing data ...",
        )
    ):
        data = data / 2210   # max-max=5419 mean-max=2210
        m = 1 - mask.astype(int)
        image = data * m

        average_edge.append((image.shape[1] + image.shape[2]) / 2)
        image = _shape_pad(image)

        s = np.linalg.svd(image, full_matrices=False, compute_uv=False)
        s0 = s[:, 0]  
        s1 = s[:, 1]  
        s2 = s[:, 2] 
        s3 = s[:, 3]  
        s4 = s[:, 4]   
        dXds1 = s0 / (s1 + np.finfo(float).eps)


        data = np.ma.MaskedArray(data, mask)
        arr = filtering(data)

        cA0, cD0 = pywt.dwt(arr, wavelet=w2, mode="constant")
        cAx, cDx = pywt.dwt(cA0[12:92], wavelet=w2, mode="constant")
        cAy, cDy = pywt.dwt(cAx[15:55], wavelet=w2, mode="constant")
        cAz, cDz = pywt.dwt(cAy[15:35], wavelet=w2, mode="constant")
        cAw2 = np.concatenate((cA0[12:92], cAx[15:55], cAy[15:35], cAz[15:25]), -1)
        cDw2 = np.concatenate((cD0[12:92], cDx[15:55], cDy[15:35], cDz[15:25]), -1)

        cA0, cD0 = pywt.dwt(arr, wavelet=w1, mode="constant")
        cAx, cDx = pywt.dwt(cA0[1:-1], wavelet=w1, mode="constant")
        cAy, cDy = pywt.dwt(cAx[1:-1], wavelet=w1, mode="constant")
        cAz, cDz = pywt.dwt(cAy[1:-1], wavelet=w1, mode="constant")
        cAw1 = np.concatenate((cA0, cAx, cAy, cAz), -1)
        cDw1 = np.concatenate((cD0, cDx, cDy, cDz), -1)

        dXdl = np.gradient(arr, axis=0)
        d2Xdl2 = np.gradient(dXdl, axis=0)
        d3Xdl3 = np.gradient(d2Xdl2, axis=0)


        fft = np.fft.fft(arr)
        real = np.real(fft)
        imag = np.imag(fft)
        ffts = np.fft.fft(s0)
        reals = np.real(ffts)
        imags = np.imag(ffts)

        # The best Feature combination for Random Forest based regression
        out_rf = np.concatenate(
            [
                arr,
                dXdl,
                d2Xdl2,
                d3Xdl3,
                dXds1,
                s0,
                s1,
                s2,
                s3,
                s4,
                real,
                imag,
                reals,
                imags,
                cAw1,
                cAw2,
            ],
            -1,
        )
        
        # The best Feature combination for KNN based regression
        out_knn = np.concatenate(
            [
                arr,
                dXdl,
                d2Xdl2,
                d3Xdl3,
                s0,
                s1,
                s2,
                s3,
                s4,
                real,
                imag,

            ],
            -1,
        )
        
      
        if is_for_KNN:
            processed_data.append(out_knn)
        else:
            processed_data.append(out_rf)

    return np.array(processed_data), np.array(average_edge)



class SpectralCurveFiltering: # Default class provided by the challenge organizers
    """
    Create a histogram (a spectral curve) of a 3D cube, using the merge_function
    to aggregate all pixels within one band. The return array will have
    the shape of [CHANNELS_COUNT]
    """

    def __init__(self, merge_function=np.mean):
        self.merge_function = merge_function

    def __call__(self, sample: np.ndarray):
        return self.merge_function(sample, axis=(1, 2))

In [7]:
# preprocessed data for random forest traninig and testing
X_tr_processed_RF, avg_edge_train = preprocess(X_train, M_train, is_for_KNN=False)
X_aug_processed_RF, avg_edge_train_aug_RF = preprocess(X_aug_train[:len(X_train)*AUGMENT_CONSTANT_RF], M_aug_train[:len(X_train)*AUGMENT_CONSTANT_RF], is_for_KNN=False)
X_te_processed_RF, avg_edge_test = preprocess(X_test, M_test, is_for_KNN=False)

# preprocessed data for KNN traninig and testing
#X_tr_processed_KNN, avg_edge_train = preprocess(X_train, M_train, is_for_KNN=True)
#X_aug_processed_KNN, avg_edge_train_aug_KNN = preprocess(X_aug_train, M_aug_train,is_for_KNN=True)
#X_te_processed_KNN, avg_edge_test = preprocess(X_test, M_test, is_for_KNN=True)

INFO: Preprocessing data ...:   0%|          | 0/1732 [00:00<?, ?it/s]

INFO: Preprocessing data ...:   0%|          | 0/1732 [00:00<?, ?it/s]

INFO: Preprocessing data ...:   0%|          | 0/1154 [00:00<?, ?it/s]

In [8]:
# Select set of labels 
y_train_col = y_train[:, COL_IX]  
y_aug_train_col = y_aug_train[:len(y_train_col)*AUGMENT_CONSTANT_RF, COL_IX]
np.shape(y_aug_train_col)

(1732, 4)

In [9]:
# Merge original data with the augmented data on training set
concatente_var= np.concatenate((X_tr_processed_RF, X_aug_processed_RF), axis=0)
concatente_target = np.concatenate((y_train_col, y_aug_train_col), axis=0)
print(np.shape(concatente_var))
print(np.shape(concatente_target))
concatente_target

(3464, 2400)
(3464, 4)

array([[ 45.1       , 188.        , 179.        ,   7.2       ],
       [ 44.8       , 205.        , 188.        ,   7.        ],
       [ 44.4       , 207.        , 145.        ,   6.8       ],
       ...,
       [ 39.42511657, 180.12790782, 121.95610079,   6.50278695],
       [ 37.29937715, 162.01316776, 126.90802342,   6.50517841],
       [ 29.50438103, 146.07037697, 133.0025748 ,   6.2953785 ]])

In [10]:
# Create a DataFrame with dummy column names
num_rows, num_cols =concatente_target.shape
#dummy_columns = [f'feat{i+1}' for i in range(num_cols)]
dummy_columns = ["P", "K", "Mg", "pH"]
y = pd.DataFrame(concatente_target, columns=dummy_columns)
# Now, 'train' is a DataFrame with dummy column names
y

              P           K          Mg        pH
0     45.100000  188.000000  179.000000  7.200000
1     44.800000  205.000000  188.000000  7.000000
2     44.400000  207.000000  145.000000  6.800000
3     46.500000  204.000000  143.000000  6.800000
4     52.000000  212.000000  167.000000  6.700000
...         ...         ...         ...       ...
3459  40.759224  133.034689  131.934234  6.201026
3460  42.671105  192.026602  125.889835  6.496557
3461  39.425117  180.127908  121.956101  6.502787
3462  37.299377  162.013168  126.908023  6.505178
3463  29.504381  146.070377  133.002575  6.295378

[3464 rows x 4 columns]

In [11]:
# Create a DataFrame with dummy column names
num_rows, num_cols =concatente_var.shape
dummy_columns = [f'feat{i+1}' for i in range(num_cols)]
train = pd.DataFrame(concatente_var, columns=dummy_columns)
# Now, 'train' is a DataFrame with dummy column names
train

,feat1,feat2,feat3,feat4,feat5,feat6,feat7,feat8,feat9,feat10,...,feat2391,feat2392,feat2393,feat2394,feat2395,feat2396,feat2397,feat2398,feat2399,feat2400
0,0.203683,0.203992,0.202177,0.205636,0.210894,0.220505,0.226073,0.227012,0.228581,0.230678,...,0.805311,0.936756,1.290456,1.626534,1.777969,2.094892,2.382082,2.567942,2.697733,2.733829
1,0.250603,0.249785,0.246786,0.250632,0.255035,0.265170,0.270217,0.269648,0.269498,0.270211,...,0.992393,1.105412,1.483055,1.721859,1.699395,2.483675,4.277375,4.606743,4.764096,4.809254
2,0.191200,0.189831,0.187725,0.191629,0.196252,0.205140,0.209914,0.210256,0.210999,0.211794,...,0.756372,0.862336,1.140623,1.386935,1.473936,1.671600,1.852783,2.015047,2.058019,2.104777
3,0.275959,0.276271,0.273568,0.278322,0.284468,0.296392,0.303449,0.305312,0.308380,0.311888,...,1.090404,1.272584,1.779799,2.184225,2.368559,2.711463,2.792593,3.004298,3.125400,3.193575
4,0.182765,0.181889,0.179319,0.182695,0.186605,0.195498,0.200748,0.201549,0.202935,0.204745,...,0.721746,0.836694,1.217127,1.562283,1.710942,2.026881,2.311239,2.532482,2.615472,2.613160
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3459,0.168458,0.168429,0.166460,0.170208,0.174657,0.183389,0.188636,0.189580,0.191368,0.193509,...,0.664630,0.789621,1.152265,1.513730,1.636141,1.871607,2.108994,2.290130,2.377135,2.392577
3460,0.205917,0.206565,0.204987,0.209040,0.214850,0.224852,0.231184,0.232514,0.234531,0.237155,...,0.812888,0.965794,1.380153,1.795300,1.943090,2.221772,2.517534,2.723252,2.864250,2.936463
3461,0.172908,0.173425,0.171930,0.175532,0.180706,0.189679,0.195410,0.196649,0.198447,0.200819,...,0.681925,0.818933,1.195239,1.568801,1.691409,1.928347,2.202613,2.378550,2.494437,2.529548
3462,0.161540,0.161888,0.160378,0.164100,0.168786,0.177497,0.182865,0.184022,0.185858,0.188017,...,0.636866,0.766576,1.115396,1.457032,1.573236,1.804500,2.087965,2.270353,2.377436,2.403943
3463,0.172338,0.172272,0.170226,0.174092,0.178568,0.187505,0.192790,0.193678,0.195408,0.197362,...,0.680051,0.805047,1.161145,1.515389,1.642185,1.884218,2.138497,2.332093,2.427869,2.446908

In [12]:
train2=pd.concat([train,y],axis=1)
train2['sample_index']=train2.index
train2

,feat1,feat2,feat3,feat4,feat5,feat6,feat7,feat8,feat9,feat10,...,feat2396,feat2397,feat2398,feat2399,feat2400,P,K,Mg,pH,sample_index
0,0.203683,0.203992,0.202177,0.205636,0.210894,0.220505,0.226073,0.227012,0.228581,0.230678,...,2.094892,2.382082,2.567942,2.697733,2.733829,45.100000,188.000000,179.000000,7.200000,0
1,0.250603,0.249785,0.246786,0.250632,0.255035,0.265170,0.270217,0.269648,0.269498,0.270211,...,2.483675,4.277375,4.606743,4.764096,4.809254,44.800000,205.000000,188.000000,7.000000,1
2,0.191200,0.189831,0.187725,0.191629,0.196252,0.205140,0.209914,0.210256,0.210999,0.211794,...,1.671600,1.852783,2.015047,2.058019,2.104777,44.400000,207.000000,145.000000,6.800000,2
3,0.275959,0.276271,0.273568,0.278322,0.284468,0.296392,0.303449,0.305312,0.308380,0.311888,...,2.711463,2.792593,3.004298,3.125400,3.193575,46.500000,204.000000,143.000000,6.800000,3
4,0.182765,0.181889,0.179319,0.182695,0.186605,0.195498,0.200748,0.201549,0.202935,0.204745,...,2.026881,2.311239,2.532482,2.615472,2.613160,52.000000,212.000000,167.000000,6.700000,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3459,0.168458,0.168429,0.166460,0.170208,0.174657,0.183389,0.188636,0.189580,0.191368,0.193509,...,1.871607,2.108994,2.290130,2.377135,2.392577,40.759224,133.034689,131.934234,6.201026,3459
3460,0.205917,0.206565,0.204987,0.209040,0.214850,0.224852,0.231184,0.232514,0.234531,0.237155,...,2.221772,2.517534,2.723252,2.864250,2.936463,42.671105,192.026602,125.889835,6.496557,3460
3461,0.172908,0.173425,0.171930,0.175532,0.180706,0.189679,0.195410,0.196649,0.198447,0.200819,...,1.928347,2.202613,2.378550,2.494437,2.529548,39.425117,180.127908,121.956101,6.502787,3461
3462,0.161540,0.161888,0.160378,0.164100,0.168786,0.177497,0.182865,0.184022,0.185858,0.188017,...,1.804500,2.087965,2.270353,2.377436,2.403943,37.299377,162.013168,126.908023,6.505178,3462
3463,0.172338,0.172272,0.170226,0.174092,0.178568,0.187505,0.192790,0.193678,0.195408,0.197362,...,1.884218,2.138497,2.332093,2.427869,2.446908,29.504381,146.070377,133.002575,6.295378,3463

In [25]:
"""gt_df = pd.read_csv(gt_data_path)
print(gt_df.shape)
gt_df.head()"""

'gt_df = pd.read_csv(gt_data_path)\nprint(gt_df.shape)\ngt_df.head()'

In [13]:
gt_p=train2[['sample_index','P']]
gt_K=train2[['sample_index','K']]
gt_Mg=train2[['sample_index','Mg']]
gt_pH=train2[['sample_index','pH']]
gt_pH.head()

   sample_index   pH
0             0  7.2
1             1  7.0
2             2  6.8
3             3  6.8
4             4  6.7

In [14]:
def reshape_dataframe(dataframe, id_vars, var_name, value_name):
    # Melt the DataFrame to reshape it
    melted = pd.melt(dataframe, id_vars=id_vars, var_name=var_name, value_name=value_name)

    # You can create the final 'sample_index' column here if needed
    melted['Target'] = melted['sample_index'].astype(str) + '_' + melted['Target']

    # Drop the 'index' column
    melted.drop('sample_index', axis=1, inplace=True)

    return melted

# Example usage
gt_p = reshape_dataframe(gt_p, id_vars=['sample_index'], var_name='Target', value_name='Value')
gt_K = reshape_dataframe(gt_K, id_vars=['sample_index'], var_name='Target', value_name='Value')
gt_Mg = reshape_dataframe(gt_Mg, id_vars=['sample_index'], var_name='Target', value_name='Value')
gt_pH = reshape_dataframe(gt_pH, id_vars=['sample_index'], var_name='Target', value_name='Value')
print(gt_pH.shape)
gt_pH.head()

(3464, 2)

  Target  Value
0   0_pH    7.2
1   1_pH    7.0
2   2_pH    6.8
3   3_pH    6.8
4   4_pH    6.7

In [15]:
# Example usage
gt_p = pd.concat([gt_p,train2],axis=1)
gt_K = pd.concat([gt_K,train2],axis=1)
gt_Mg = pd.concat([gt_Mg,train2],axis=1)
gt_pH = pd.concat([gt_pH,train2],axis=1)
train = pd.concat([gt_p,gt_K,gt_Mg,gt_pH],axis=0)
train.to_csv('train.csv',index=False)
print(train.shape)
train.head()

(13856, 2407)

,Target,Value,feat1,feat2,feat3,feat4,feat5,feat6,feat7,feat8,...,feat2396,feat2397,feat2398,feat2399,feat2400,P,K,Mg,pH,sample_index
0,0_P,45.1,0.203683,0.203992,0.202177,0.205636,0.210894,0.220505,0.226073,0.227012,...,2.094892,2.382082,2.567942,2.697733,2.733829,45.1,188.0,179.0,7.2,0
1,1_P,44.8,0.250603,0.249785,0.246786,0.250632,0.255035,0.265170,0.270217,0.269648,...,2.483675,4.277375,4.606743,4.764096,4.809254,44.8,205.0,188.0,7.0,1
2,2_P,44.4,0.191200,0.189831,0.187725,0.191629,0.196252,0.205140,0.209914,0.210256,...,1.671600,1.852783,2.015047,2.058019,2.104777,44.4,207.0,145.0,6.8,2
3,3_P,46.5,0.275959,0.276271,0.273568,0.278322,0.284468,0.296392,0.303449,0.305312,...,2.711463,2.792593,3.004298,3.125400,3.193575,46.5,204.0,143.0,6.8,3
4,4_P,52.0,0.182765,0.181889,0.179319,0.182695,0.186605,0.195498,0.200748,0.201549,...,2.026881,2.311239,2.532482,2.615472,2.613160,52.0,212.0,167.0,6.7,4

In [16]:
np.shape(X_te_processed_RF)

(1154, 2400)

In [17]:
np.shape(X_tr_processed_RF)

(1732, 2400)

In [18]:
# Create a DataFrame with dummy column names
num_rows, num_cols = X_te_processed_RF.shape
dummy_columns = [f'feat{i+1}' for i in range(num_cols)]
test = pd.DataFrame(X_te_processed_RF, columns=dummy_columns)
# Assuming you have a DataFrame 'test', create the 'Target' column
test_P=test.copy()
test_K=test.copy()
test_Mg=test.copy()
test_PH=test.copy()

test_P['Target'] = [f'{i}_P' for i in range(len(test_P))]
test_P['mean_norm'] = 70.3026558891455
#70.3026558891455,227.9885103926097,159.28123556581986,6.782719399538106
test_K['Target'] = [f'{i}_K' for i in range(len(test_K))]
test_K['mean_norm'] = 227.9885103926097

test_Mg['Target'] = [f'{i}_Mg' for i in range(len(test_Mg))]
test_Mg['mean_norm'] = 159.28123556581986

test_PH['Target'] = [f'{i}_pH' for i in range(len(test_PH))]
test_PH['mean_norm'] = 6.782719399538106

test=pd.concat([test_P,test_K,test_Mg,test_PH],axis=0)

# Now, your 'Target' column in the test DataFrame will have values like '0_P', '1_P', '2_P', and so on.
print(test.shape)
test.to_csv('test.csv',index=False)

# Now, 'train' is a DataFrame with dummy column names
test

(4616, 2402)

,feat1,feat2,feat3,feat4,feat5,feat6,feat7,feat8,feat9,feat10,...,feat2393,feat2394,feat2395,feat2396,feat2397,feat2398,feat2399,feat2400,Target,mean_norm
0,0.173565,0.171952,0.168504,0.170999,0.173946,0.181525,0.185026,0.184056,0.183710,0.183698,...,1.174493,1.269823,1.064050,1.963784,4.521961,5.065660,5.246762,5.330273,0_P,70.302656
1,0.202796,0.201845,0.199020,0.202500,0.206132,0.214863,0.219335,0.218668,0.218889,0.219440,...,1.248479,1.495482,1.494265,2.381440,4.517328,4.982208,5.206562,5.262480,1_P,70.302656
2,0.164810,0.163459,0.161074,0.163151,0.166365,0.173361,0.176534,0.175363,0.174817,0.174266,...,1.169714,1.269090,0.967839,2.094396,5.501404,6.153006,6.340413,6.413906,2_P,70.302656
3,0.196746,0.195933,0.192789,0.195939,0.199449,0.207141,0.210958,0.209670,0.209044,0.208800,...,1.135058,1.346569,1.292224,2.551541,5.902475,6.501725,6.768157,6.804711,3_P,70.302656
4,0.265508,0.266124,0.264145,0.268839,0.274781,0.286389,0.293448,0.294926,0.297448,0.300688,...,1.668053,2.016291,2.163232,2.443648,2.528219,2.715599,2.822610,2.819261,4_P,70.302656
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1149,0.201331,0.201670,0.199746,0.204116,0.209300,0.219236,0.225269,0.226503,0.228633,0.231030,...,1.355050,1.761454,1.890163,2.161619,2.482829,2.687889,2.808897,2.861287,1149_pH,6.782719
1150,0.187588,0.188071,0.186565,0.190504,0.195775,0.205280,0.211257,0.212602,0.214667,0.217173,...,1.292950,1.703421,1.837563,2.098486,2.399257,2.591536,2.715855,2.773716,1150_pH,6.782719
1151,0.246595,0.247139,0.245130,0.250370,0.256538,0.268103,0.275224,0.276892,0.279748,0.283008,...,1.646616,2.134732,2.322334,2.661394,2.926015,3.165880,3.297552,3.393916,1151_pH,6.782719
1152,0.195533,0.196011,0.194421,0.198574,0.203896,0.213583,0.219580,0.220892,0.222968,0.225395,...,1.307993,1.691528,1.829480,2.100164,2.407549,2.618703,2.759835,2.830244,1152_pH,6.782719
1153,0.162502,0.162253,0.160069,0.163695,0.167853,0.176373,0.181360,0.182229,0.183950,0.185722,...,1.095332,1.429914,1.542066,1.766857,2.017786,2.205045,2.280156,2.291676,1153_pH,6.782719